name: Rust Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login
      run: cargo login ${{ secrets.DERIVE_CTOR_API_KEY }}
    - name: Deploy
      run: cargo publish
