name: Rust CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.DERIVE_CTOR_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login
      run: cargo login
    - name: Deploy
      run: cargo publish
